### ISSUE TITLE
Error: no available ports

### ISSUE THREAD

**Issue by JoeeyIreland** [Polymer/tools#1150]
when i run polymer serve -H [78.68.84.107] it brings up a error that no ports are available and shows a ton of port numbers. i have tried with sudo before but still no fix.

I'm running a 1&1 cloud server running CentOS7 and my node.js is 7.10.1

i cannot figure out why this is not working

**Comment by maboelsoudd2l** [comment]
Any updates on this? I try to serve on my local hostname and get this error.
```
ERROR: Server failed to start: Error: No available ports. Ports tried: [8081,8000,8001,8003,8031,2000,2001,2020,2109,2222,2310,3000,3001,3030,3210,3333,4000,4001,4040,4321,4502,4503,4567,5000,5001,5050,5432,6000,6001,6060,6666,6543,7000,7070,7774,7777,8765,8777,8888,9000,9001,9080,9090,9876,9877,9999,49221,55001]
    at /<path>/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:388:15
    at Generator.next (<anonymous>)
    at fulfilled (/<path>/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:17:58)
error:	cli runtime exception: Error: Error: No available ports. Ports tried: [8081,8000,8001,8003,8031,2000,2001,2020,2109,2222,2310,3000,3001,3030,3210,3333,4000,4001,4040,4321,4502,4503,4567,5000,5001,5050,5432,6000,6001,6060,6666,6543,7000,7070,7774,7777,8765,8777,8888,9000,9001,9080,9090,9876,9877,9999,49221,55001]
error:	Error: Error: No available ports. Ports tried: [8081,8000,8001,8003,8031,2000,2001,2020,2109,2222,2310,3000,3001,3030,3210,3333,4000,4001,4040,4321,4502,4503,4567,5000,5001,5050,5432,6000,6001,6060,6666,6543,7000,7070,7774,7777,8765,8777,8888,9000,9001,9080,9090,9876,9877,9999,49221,55001]
    at /<path>/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:93:19
    at Generator.throw (<anonymous>)
    at rejected (/<path>/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:18:65)
```
