### ISSUE TITLE
[bundler] Bundled build fails when using import.meta.url

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#204]
### Description

See the [original comment](https://github.com/Polymer/polymer-bundler/issues/624#issuecomment-382315943). As the bundler repo is already archived, I'm starting a new discussion here.

The bunded build fails because of rollup hanging on `import.meta`:

```sh
$ polymer build --entrypoint test.html --npm --module-resolution=node --js-transform-modules-to-amd --bundle
info: [cli.command.build]    Clearing build/ directory...
error: [cli.main]   Promise rejection: Error: Unexpected token
error: [cli.main]   Error: Unexpected token
    at error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:168:15)
    at Module.error (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:19072:9)
    at tryParse (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18763:16)
    at Module.setSource (/Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:18818:24)
    at /Users/sergey/.nvm/versions/node/v8.11.1/lib/node_modules/polymer-cli/node_modules/rollup/dist/rollup.js:21457:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

This happens because AMD transform is performed after bundling (which is quite reasonable).
So far I didn't find any relevant issue in the [rollup](https://github.com/rollup/rollup/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+import.meta) repo regarding this topic.

### Versions & Environment
- Polymer CLI: 1.7.0-pre.13
- node: 8.11.1
- Operating System: Mac OS

### Use Case

We only have one use case, but that one is really important for us. The goal is to detect whether the app as bundled or not, from the JS code. This is needed to disable some environment-related logic.

For Polymer 3 and the native `import.meta.url` implementation in Chrome, this (to my understanding) should be as easy as follows:
```js
let isUnbundled = this.importPath.endsWith(`${this.constructor.is}.js`);
```

For Polymer 2, we are still able to do recursive HTML imports check and detect if the specific import is loaded, so no need for file name and extension in the `importPath` property for us there.

**Comment by web-padawan** [comment]
Closing in favor of #294
