### ISSUE TITLE
[build] Node 10 possible incompatibility with the `temp` package used in tests

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#236]
Manifests in a single error from polymer-build tests in `service-worker_test.ts`
```
     Uncaught RangeError [ERR_OUT_OF_RANGE]: The value of "mode" is out of range. Received 16877
      at Object.fs.fchmod (fs.js:1024:11)
      at Object.fchmod (node_modules/graceful-fs/polyfills.js:237:17)
      at mode (node_modules/vinyl-fs/lib/fileOperations.js:132:10)
      at onStat (node_modules/vinyl-fs/lib/fileOperations.js:125:14)
      at node_modules/graceful-fs/polyfills.js:287:18
      at FSReqWrap.oncomplete (fs.js:150:5)
```

![screenshot](https://user-images.githubusercontent.com/578/39268882-f5e36cb6-4885-11e8-8d1a-44eb5d3d2137.png)

**Comment by sebs** [comment]
same here.
