### ISSUE TITLE
Installation with Yarn global crashes `polymer test`

### ISSUE THREAD

**Issue by TimvdLippe** [Polymer/tools#2398]
### Description

I install the polymer-cli with Yarn (`yarn global add polymer-cli@next`), but it seems to crash when running `polymer test` on a new project.

### Versions & Environment
- Polymer CLI: polymer-cli@0.18.0-pre.15
- node: v7.7.3
- Operating System: Ubuntu 16.04

#### Steps to Reproduce

1. `yarn global add polymer-cli@next`
2. `mkdir psk && cd psk && polymer init` to install `polymer-2-starter-kit`
3. `polymer test`

#### Expected Results

Tests run with web-component-tester.

#### Actual Results

```js
tim@tim-HP-ZBook-15:~/Projects/psk$ polymer test
error:   cli runtime exception: Error: Cannot find module '../build/safe-execute'
error:   Error: Cannot find module '../build/safe-execute'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/tim/.config/yarn/global/node_modules/wd/lib/commands.js:21:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

Installation with `npm install -g polymer-cli@next` and the other reproduction steps works just fine. It seems that the post-install commands are not invoked when installing with `Yarn`?

**Comment by Exnadella** [comment]
Hi, We are facing a similar issue and we are using Travis-CI builder.  Please find the log attached from the build.  We are using one of the .travis.yml files from one of the polymer web components.

https://app.travis-ci.com/github/ExcentITSolutionspvtltd/DEPLOYMENT-TEST-URCASH/builds/253797287


![image](https://user-images.githubusercontent.com/22579094/181816070-be845b24-ee66-4980-86a8-df0d3f377e98.png)
![image](https://user-images.githubusercontent.com/22579094/181816153-a168cd96-7863-4f98-8021-777d6f6d689a.png)
![image](https://user-images.githubusercontent.com/22579094/181816233-728089df-d625-4f30-b7f5-e891ba59591f.png)
![image](https://user-images.githubusercontent.com/22579094/181816357-37aaad95-827a-4f15-a2e2-ac923aec9f78.png)

Thanks,
Ranganath.
