### ISSUE TITLE
[appveyor] Weird permissions issue renaming file on install (intermittent error)

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#244]
```
Build started
git clone -q https://github.com/Polymer/tools.git C:\projects\tools
git fetch -q origin +refs/pull/243/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
Install-Product node $env:nodejs_version
Uninstalling node 4.8.7 (x86)...
Installing node 9.11.1 (x86)...
npm install
added 332 packages in 6.214s
rm packages/*/package-lock.json
npm run bootstrap
> polymer-tools@ bootstrap C:\projects\tools
> lerna bootstrap
lerna info version 2.10.2
lerna info versioning independent
lerna info Bootstrapping 11 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
lerna ERR! npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
lerna ERR! npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
lerna ERR! npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
lerna ERR! npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
lerna ERR! npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
lerna ERR! npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
lerna ERR! npm WARN build No repository field.
lerna ERR! npm WARN build No license field.
lerna ERR! 
lerna ERR! npm ERR! path C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919
lerna ERR! npm ERR! code EPERM
lerna ERR! npm ERR! errno -4048
lerna ERR! npm ERR! syscall rename
lerna ERR! npm ERR! Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
lerna ERR! npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
lerna ERR! npm ERR!   cause: 
lerna ERR! npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
lerna ERR! npm ERR!      errno: -4048,
lerna ERR! npm ERR!      code: 'EPERM',
lerna ERR! npm ERR!      syscall: 'rename',
lerna ERR! npm ERR!      path: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919',
lerna ERR! npm ERR!      dest: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js' },
lerna ERR! npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\' -> \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js\'',
lerna ERR! npm ERR!   errno: -4048,
lerna ERR! npm ERR!   code: 'EPERM',
lerna ERR! npm ERR!   syscall: 'rename',
lerna ERR! npm ERR!   path: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919',
lerna ERR! npm ERR!   dest: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js' }
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Please try running this command again as root/Administrator.
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-04-26T01_12_17_163Z-debug.log
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (C:\projects\tools\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
{ Error: Command failed: npm install
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN build No repository field.
npm WARN build No license field.
npm ERR! path C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
npm ERR!   cause: 
npm ERR!    { Error: EPERM: operation not permitted, rename 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js.715743919' -> 'C:\projects\tools\packages\build\node_modules\requirejs\bin\r.js'
npm ERR!      errno: -4048,
npm ERR!      code: 'EPERM',
npm ERR!      syscall: 'rename',
npm ERR!      path: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919',
npm ERR!      dest: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js' },
npm ERR!   stack: 'Error: EPERM: operation not permitted, rename \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\' -> \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js\'',
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919',
npm ERR!   dest: 'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-04-26T01_12_17_163Z-debug.log
    at Promise.all.then.arr (C:\projects\tools\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 4294963248,
  killed: false,
  stdout: '',
  stderr: 'npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5\nnpm WARN deprecated formatio@1.1.1: This package is unmaintained. Use @sinonjs/formatio instead\nnpm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated natives@1.1.3: This module relies on Node.js\'s internals and will break at some point. Do not use it, and update to graceful-fs@4.x.\nnpm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue\nnpm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js\nnpm WARN build No repository field.\nnpm WARN build No license field.\n\nnpm ERR! path C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\nnpm ERR! code EPERM\nnpm ERR! errno -4048\nnpm ERR! syscall rename\nnpm ERR! Error: EPERM: operation not permitted, rename \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\' -> \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js\'\nnpm ERR!  { Error: EPERM: operation not permitted, rename \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\' -> \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js\'\nnpm ERR!   cause: \nnpm ERR!    { Error: EPERM: operation not permitted, rename \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js.715743919\' -> \'C:\\projects\\tools\\packages\\build\\node_modules\\requirejs\\bin\\r.js\'\nnpm ERR!      errno: -4048,\nnpm ERR!      code: \'EPERM\',\nnpm ERR!      syscall: \'rename\',\nnpm ERR!      path: \'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js.715743919\',\nnpm ERR!      dest: \'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js\' },\nnpm ERR!   stack: \'Error: EPERM: operation not permitted, rename \\\'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js.715743919\\\' -> \\\'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js\\\'\',\nnpm ERR!   errno: -4048,\nnpm ERR!   code: \'EPERM\',\nnpm ERR!   syscall: \'rename\',\nnpm ERR!   path: \'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js.715743919\',\nnpm ERR!   dest: \'C:\\\\projects\\\\tools\\\\packages\\\\build\\\\node_modules\\\\requirejs\\\\bin\\\\r.js\' }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\_logs\\2018-04-26T01_12_17_163Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! polymer-tools@ bootstrap: `lerna bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the polymer-tools@ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2018-04-26T01_12_55_526Z-de
```

**Comment by web-devel** [comment]
Constantly experience the same issue on Windows machines. It seems it's a bug with npm itself: https://github.com/npm/npm/issues/19934

**Comment by dengxiao0509** [comment]
any progress here? @usergenic
