### ISSUE TITLE
Node 10: TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by pdesjardins90** [Polymer/tools#3261]
After upgrading node, WCT doesn't work anymore. The error is: 
`TypeError: Cannot read property '1' of null`

Node v10.0.0
WCT version: 6.5

Steps to reproduce:
- polymer init (shop app)
- polymer test

Stack trace:

```
cli runtime exception: TypeError: Cannot read property '1' of null
error:   TypeError: Cannot read property '1' of null
    at module.exports (/Users/x/.config/yarn/global/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at processExports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:82:25)
    at module.exports (/Users/x/.config/yarn/global/node_modules/promisify-node/index.js:164:10)
    at /Users/x/.config/yarn/global/node_modules/web-component-tester/runner/paths.js:49:23
    at Generator.next (<anonymous>)
    at /Users/x/.config/yarn/global/node_modules/web-component-tester/runner/paths.js:20:71
    at new Promise (<anonymous>)
```

**Comment by mdaijaj** [comment]
I found this error then I re-install express module.
