### ISSUE TITLE
Does polyserve still use bower?

### ISSUE THREAD

**Issue by danielmatthew** [Polymer/tools#3356]
Hi!

Installed `polymer-cli@1.9.6`, and attempted to `serve` an element I had created with `lit-element` [following the documentation](https://lit-element.polymer-project.org/guide/start), only to see the following error:

```
➜  lit-element polymer serve
Starting Polyserve...
    serving on port: 8080
    from root: /Users/dm/lit-element

Error reading config at /Users/dm/lit-element/bower.json
{ Error: ENOENT: no such file or directory, open '/Users/dm/lit-element/bower.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at bowerConfigContents (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/bower_config.js:20:23)
    at Object.bowerConfig (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/bower_config.js:30:27)
    at Object.makeApp (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/make_app.js:30:63)
    at getApp (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:59:34)
    at startWithPort (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:101:17)
    at Promise.then (/usr/local/lib/node_modules/polymer-cli/node_modules/polyserve/lib/start_server.js:43:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/dm/lit-element/bower.json' }
Files in this directory are available under the following URLs
    applications: http://localhost:8080
    reusable components: http://localhost:8080/components/lit-element/
^C
```

I thought this might have been the case back in the days of Polymer 1 and 2, but a little confused about this requirement.  

---

Polymer CLI is installed globally.

**Comment by danielmatthew** [comment]
Urgh. Ignore me. Some kind of error in how packages are installed on this machine. When I run `polymer help` I get the

```
╭────────────────────────────────────────╮
   │                                        │
   │    Update available 0.17.0 → 1.9.6     │
   │   Run npm i -g polymer-cli to update   │
   │                                        │
   ╰────────────────────────────────────────╯
```

message.
