### ISSUE TITLE
Polymer-cli install error

### ISSUE THREAD

**Issue by MatheusR98** [Polymer/tools#3413]
Description

npm error when running npm install -g polymer-cli as root.

Versions & Environment

    node: 8.11.1
    npm: 6.9.0
    Operating System: MasOS Sierra 10.12.6

Steps to Reproduce

To reproduce, build this in Terminal:

sudo npm install -y polymer-cli

Expected Results

NPM should install polymer-cli without an error.
Actual Results

We get an error in the output:

npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module './access-error.js'

and gives me a full log, dropped below
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'polymer-cli' ]
2 info using npm@6.9.0
3 info using node@v8.11.1
4 verbose config Skipping project config: /Users/matheus.ribeiro/.npmrc. (matches userconfig)
5 verbose stack Error: Cannot find module './access-error.js'
5 verbose stack     at Function.Module._resolveFilename (module.js:547:15)
5 verbose stack     at Function.Module._load (module.js:474:25)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/exists.js:4:19)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
5 verbose stack     at Module.load (module.js:565:32)
5 verbose stack     at tryModuleLoad (module.js:505:12)
5 verbose stack     at Function.Module._load (module.js:497:3)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/install/check-permissions.js:8:14)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
5 verbose stack     at Module.load (module.js:565:32)
6 verbose cwd /Users/matheus.ribeiro
7 verbose Darwin 16.7.0
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "polymer-cli"
9 verbose node v8.11.1
10 verbose npm  v6.9.0
11 error code MODULE_NOT_FOUND
12 error Cannot find module './access-error.js'
13 verbose exit [ 1, true ]

What do i do?

**Comment by MatheusR98** [comment]
Installed again Git and node, found response in other topic... [this](https://github.com/Polymer/tools/issues/2502)
