### ISSUE TITLE
Breaking change in vscode-uri affected polymer-analyzer

### ISSUE THREAD

**Issue by web-padawan** [Polymer/tools#3425]
The `vscode-uri` dependency has been recently bumped to `1.0.7` and they included breaking changes in a patch release. See the commit: https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634

In particular, default export has been removed and changed to named export which results in errors:

```console
error:	cli runtime exception: TypeError: Cannot read property 'file' of undefined
error:	TypeError: Cannot read property 'file' of undefined
    at new FsUrlResolver (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-analyzer/lib/url-loader/fs-url-resolver.js:48:55)
    at new PackageUrlResolver (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-analyzer/lib/url-loader/package-url-resolver.js:27:9)
    at ProjectConfig.<anonymous> (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-project-config/lib/index.js:301:33)
    at Generator.next (<anonymous>)
    at /home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-project-config/lib/index.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-project-config/lib/index.js:16:12)
    at ProjectConfig.initializeAnalyzer (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-project-config/lib/index.js:299:16)
    at Object.<anonymous> (/home/travis/build/vaadin/vaadin-time-picker/node_modules/polymer-cli/lib/lint/lint.js:74:82)
```

In the meanwhile, as a workaround we have to pin to `=1.0.6` explicitly.

**Comment by web-padawan** [comment]
Reported at https://github.com/microsoft/vscode/issues/74533

**Comment by web-padawan** [comment]
The original issue has been fixed, closing.
