### ISSUE TITLE
polymer-build error "[UriError]: Scheme is missing"

### ISSUE THREAD

**Issue by govis** [Polymer/tools#3432]
I have a <code>gulpfile.js</code> that largely mirrors <code>polymer-cli\lib\build\build.js</code> with a few minor tweaks. Unfortunately <code>polymer-build</code> is throwing an error:
<pre><code>Error: Could not load file:///f%3A/x/node_modules/%40polymer/polymer/lib/mixins/element-mixin.js (imported by *bundle*): [UriError]: Scheme is missing: {scheme: "", authority: "", path: "node_modules/@polymer/polymer/lib/mixins/element-mixin.js", query: "", fragment: ""}
    at _validateUri (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\vscode-uri\lib\umd\index.js:52:23)
    at _URI.URI (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\vscode-uri\lib\umd\index.js:153:17)
    at new _URI (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\vscode-uri\lib\umd\index.js:355:51)
    at Function.URI.parse (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\vscode-uri\lib\umd\index.js:265:20)
    at Object.ensureLeadingDot (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\polymer-bundler\lib\url-utils.js:40:31)
    at Object.load (C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\polymer-bundler\lib\es6-rewriter.js:123:65)
    at C:\Users\x\AppData\Roaming\npm\node_modules\polymer-build\node_modules\rollup\dist\rollup.js:15429:25
    at processTicksAndRejections (internal/process/task_queues.js:89:5)</code></pre>

This is on Node v12.4.0

**Comment by web-padawan** [comment]
Appears to be related to https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634#r33726484

See also #3425 

/cc @usergenic looks like we need to pin `vscode-uri` to `=1.0.6`, as I previously suggested.

**Comment by aomarks** [comment]
We recently pinned `vscode-uri` in https://github.com/microsoft/vscode-uri/commit/7f15d244457fd4e09c88264c676dc915beffb634. So, we need to do a patch release of any affected tool. I guess at least bundler and cli, maybe some others?

**Comment by web-padawan** [comment]
FYI `linter` are `modulizer` don't seem to be affected (at least they work in our CI with 1.0.8).

**Comment by aomarks** [comment]
We just published polymer-analyzer@3.2.3 and polymer-bundler@4.0.10, which I think should cover the affected tools.
