### ISSUE TITLE
Error with wct - mout/lang

### ISSUE THREAD

**Issue by drewswaycool** [Polymer/tools#3470]
Several web component repos are failing preventing our CI build from running tests.

```
npx wct --configFile wct.conf.windows.json --skip-plugin local && npx wct --configFile wct.conf.json --skip-plugin local
module.js:550
    throw err;
    ^
Error: Cannot find module 'mout/lang'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/fs-webdev/fs-add-person/node_modules/bower-config/lib/Config.js:1:74)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
```

**Comment by drewswaycool** [comment]
Perhaps something changed.. this is no longer an issue.
