### ISSUE TITLE
Can't get Polymer-cli installed

### ISSUE THREAD

**Issue by jongmana** [Polymer/tools#369]
I tried to install the polymer-cli with node 8.x and 10.x as well as with npm 5.6.0 and the latest npm but with no success.
Node 8.11.1 with the latest npm gives serveral "npm ERR! write after end" errors before it stops.

I had set up this dockerfile to for the polymer install:

```
FROM node:8.11.1

RUN apt-get update \
  && apt-get -y upgrade
RUN apt-get -y install \
    apt-utils \
    sudo \
    git

RUN npm install -g npm@latest

RUN npm install -g polymer-cli

RUN useradd --create-home --home-dir /home/nonroot --shell /bin/bash nonroot \
  && echo "nonroot:root" | chpasswd \
  && adduser nonroot sudo

EXPOSE 8081

USER nonroot

WORKDIR /home/nonroot

ENTRYPOINT ["bash"]
```

**Comment by jongmana** [comment]
By adding 

`RUN npm install -g types-installer`

just before the installation of polymer-cli I could get rid of the write after end errors, but now I got stuck at the installation of wd during the polymer-cli installation:

> wd@1.6.2 install /usr/local/lib/node_modules/polymer-cli/node_modules/wd
> node scripts/build-browser-scripts
>
> /usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:90
>
>                   throw err0;
>                   ^
>
>Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/polymer-cli/node_modules/wd/build'
>   at Object.fs.mkdirSync (fs.js:854:3)
>    at sync (/usr/local/lib/node_modules/polymer-cli/node_modules/mkdirp/index.js:71:13)
>    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/wd/scripts/build-browser-scripts.js:6:1)
>    at Module._compile (internal/modules/cjs/loader.js:678:30)
>    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
>    at Module.load (internal/modules/cjs/loader.js:589:32)
>    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
>    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
>    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
>    at startup (internal/bootstrap/node.js:228:19)
>npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.3 (node_modules/polymer-cli/node_modules/fsevents):
>npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
>
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! wd@1.6.2 install: `node scripts/build-browser-scripts`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the wd@1.6.2 install script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by jongmana** [comment]
I managed to get it working, by chaning the polymer-cli install instruction to:
```
RUN npm install -g types-installer
RUN npm install -g polymer-cli --allow-root --unsafe-perm=true
```

But I hope that this will not result in errors working with this polymer docker image.
