### ISSUE TITLE
Running polymer scripts from package.json

### ISSUE THREAD

**Issue by jordanfinners** [Polymer/tools#385]
Hi, in the recent 1.7.x release there seems to be an issue if you try and run the polymer command using a script in the package.json. e.g. `npm run polymer-test` which runs `polymer test -l chrome`

This is also happening for `polymer lint` 
Here is a snippet from the npm logs

This is becoming a pain to work around in the CI process

`1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@6.0.1
3 info using node@v10.1.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
10 silly lifecycle folder@~test: Args: [ '-c', 'polymer test -l chrome' ]
11 silly lifecycle folder@~test: Returned: code: 1  signal: null
12 info lifecycle folder@~test: Failed to exec test script
13 verbose stack Error: folder@ test: `polymer test -l chrome`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:957:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
14 verbose pkgid folder@
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
18 verbose node v10.1.0
19 verbose npm  v6.0.1
20 error code ELIFECYCLE
21 error errno 1
`

**Comment by rictic** [comment]
I'm unable to repro this: https://github.com/rictic/repro-tools-issue-385

```
git clone git@github.com:rictic/repro-tools-issue-385.git
cd repro-tools-issue-385
npm install && npm test && npm run lint
```

This succeeds for me.
