### ISSUE TITLE
polymer cannot build using bundle option

### ISSUE THREAD

**Issue by lazex** [Polymer/tools#519]
`polymer build`  works, but `polymer build --bundle` is not.
I thought that there is an error in my code, and I create new project using `polymer init`.
However, same error occurred.

Starter template is `polymer-3-application`

```
user@localhost ~/polymer> polymer build --bundle
info: [cli.command.build]    Clearing build/ directory...
error: [cli.main]   Promise rejection: Error: Document wasn't an JS document, it's a: document,html-document
error: [cli.main]   Error: Document wasn't an JS document, it's a: document,html-document
    at Object.assertIsJsDocument (/home/user/n/lib/node_modules/polymer-cli/node_modules/polymer-bundler/lib/analyzer-utils.js:29:15)
    at Es6Rewriter.<anonymous> (/home/user/n/lib/node_modules/polymer-cli/node_modules/polymer-bundler/lib/es6-rewriter.js:135:48)
    at Generator.next (<anonymous>)
    at fulfilled (/home/user/n/lib/node_modules/polymer-cli/node_modules/polymer-bundler/lib/es6-rewriter.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:178:7)

user@localhost ~/t/polymer> polymer --version
1.7.3
```

Is it a bug?

**Comment by leonrinkel** [comment]
polymer.json needs additional Polymer 3 specific parameters. The following addition made it for me:
```
  "entrypoint": "index.html",
  "shell": "src/web-app/web-app.js",
  "sources": [
    "src/**.js",
    "package.json"
  ],
```

**Comment by lazex** [comment]
Thank you for your advice.
I retried in polymer-cli 1.7.7, and it worked without additional settings.
