### ISSUE TITLE
AssertionError trying to save already-saved file part

### ISSUE THREAD

**Issue by araker** [Polymer/tools#522]
When using polymer build I get the following error. I've used the --verbose flag to get more output. 

```
debug: [cli.build.analyzer]   addFile: /myhome/polymer-app/bower_components/paper-material/paper-material-shared-styles.html
error: [cli.main]   Promise rejection: AssertionError [ERR_ASSERTION]: Trying to save already-saved file part "/myhome/polymer-app/bower_components/iron-meta/iron-meta.html_script_0.js".
error: [cli.main]   AssertionError [ERR_ASSERTION]: Trying to save already-saved file part "/myhome/polymer-app/bower_components/iron-meta/iron-meta.html_script_0.js".
    at SplitFile.setPartContent (/myhome/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:140:9)
    at HtmlRejoinTransform._transformIter_2 (/myhome/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:253:40)
    at _transformIter_2.next (<anonymous>)
    at resume (/myhome/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:34:44)
    at fulfill (/myhome/.nvm/versions/node/v8.9.4/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/html-splitter.js:36:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
This error is very similar to [this ticket](https://github.com/Polymer/polymer-cli/issues/881), unfortunately the workarounds from that ticket, reverting back to v1.3.1 or removing the fragments part from polymer.json do not work for me. I've also tried v1.4.1 and v1.7.1, which gave the same error. 

This is the build section of my polymer.json 

```
    "builds": [
        {
            "name": "es5-unbundled",
            "addServiceWorker": true,
            "html": {
                "minify": false
            },
            "css": {
                "minify": false
            },
            "js": {
                "compile": true,
                "minify": false
            },
            "bundle": false,
            "addPushManifest": false,
            "insertPrefetchLinks": false
        }
    ],
```

I'm using v1.7.3 of the polymer cli, code is polymer-2, working on ubuntu 16.04.

**Comment by araker** [comment]
Closing this, since the issue magically disappeared this morning.
