### ISSUE TITLE
Callback was already called error

### ISSUE THREAD

**Issue by sikrit** [Polymer/tools#535]
```
Failed to download selenium and/or chromedriver: Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-win64.zip: Error: read ECONNRESET
    at Request.<anonymous> (Yarn\\Data\\global\\node_modules\\selenium-standalone\\lib\\install.js:386:12)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (Yarn\\Data\\global\\node_modules\\request\\request.js:877:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
selenium-standalone will attempt to re-download next time it is run.
Yarn\\Data\\global\\node_modules\\async\\dist\\async.js:966
        **if (fn === null) throw new Error(\"Callback was already called.\");**
                         ^

**Error: Callback was already called.**
    at Yarn\\Data\\global\\node_modules\\async\\dist\\async.js:966:32
    at Local\\Yarn\\Data\\global\\node_modules\\async\\dist\\async.js:3885:13
    at onOpenZipFile (Yarn\\Data\\global\\node_modules\\selenium-standalone\\lib\\install.js:401:9)
    at Yarn\\Data\\global\\node_modules\\yauzl\\index.js:36:7
    at Yarn\\Data\\global\\node_modules\\yauzl\\index.js:183:5
```

Cannot install **polymer-cli**, getting same error with Yarn and with npm as well.

**Comment by jsilvermist** [comment]
Not getting this exact error, but when I updated to 1.7.4 I had to manually install `selenium-standalone` to be able to run `polymer test`. Not sure if related or not.

**Comment by sikrit** [comment]
Cleared cache, uninstalled `polymer-cli`, then manually installed `selenium-standalone` and finally again `polymer-cli` with no errors.
