### ISSUE TITLE
[wct] `import.meta` bombs the process

### ISSUE THREAD

**Issue by Westbrook** [Polymer/tools#564]
When attempting to use `import.meta.url` to empower `new URL()` to create import relative URLs, I am able to get `polymer serve` and `polymer build` to work with seemingly no issue, however `polymer test` bombs out when run against even an unused application of this concept: 
```
let url = import.meta.url;
```
Let alone a version that would empower my element to import local assets:
```
let url = new URL(
  path,
  import.meta.url
);
```
My config looks like the following:
```
{
  "verbose": false,
  "plugins": {
    "local": {
      "browsers": ["chrome"],
      "browserOptions": {
        "chrome": ["headless", "disable-gpu", "no-sandbox"],
        "firefox": ["-headless"]
      }
    },
    "sauce": {
      "disabled": true,
      "username": "redacted",
      "accessKey": "redacted",
      "browsers": [
        {
          "browserName": "firefox",
          "platform": "Windows 10",
          "version": "60"
        },
        {
          "browserName": "microsoftedge",
          "platform": "Windows 10",
          "version": ""
        },
        {
          "browserName": "safari",
          "platform": "OS X 10.12",
          "version": "11"
        }
      ]
    },
    "istanbub": {
      "dir": "./coverage",
      "reporters": ["text", "lcov"],
      "include": ["/*.js"],
      "thresholds": {
        "global": {
          "statements": 100,
          "branches": 96,
          "functions": 100,
          "lines": 100
        }
      }
    }
  }
}
```
Is there something that I've missed?

**Comment by aomarks** [comment]
Can you include the output/crash log?

**Comment by Westbrook** [comment]
Here ya go @aomarks. The same tests run in the browser pass as well (baring the lowdash issue of not having exports).

Versions:
polymer-cli@1.7.7
polymer-build@3.0.4
web-component-tester@6.7.1

```
Installing and starting Selenium server for local browsers
Selenium server running on port 43519
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
chrome 66                Beginning tests via http://localhost:8081/components/@lingolive/course-catalog/generated-index.html?cli_browser_id=3
chrome failed to maximize
SyntaxError: Unexpected token, expected ( (139:22)
    at Parser.pp$5.raise (/home/circleci/project/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/circleci/project/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:3632:14)
    at Parser.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/home/circleci/project/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/circleci/project/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/circleci/project/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/circleci/project/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:6474:20)
SyntaxError: Unexpected token, expected ( (139:22)
    at Parser.pp$5.raise (/home/circleci/project/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/circleci/project/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:3632:14)
    at Parser.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/home/circleci/project/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/circleci/project/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/circleci/project/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/circleci/project/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:6474:20)
SyntaxError: Unexpected token, expected ( (139:22)
    at Parser.pp$5.raise (/home/circleci/project/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/circleci/project/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:3632:14)
    at Parser.parseExprAtom (/home/circleci/project/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/home/circleci/project/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/circleci/project/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/circleci/project/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/circleci/project/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/circleci/project/node_modules/babylon/lib/index.js:6474:20)
```

**Comment by usergenic** [comment]
@Westbrook can you say how your polymer-cli is installed?  Do you use `npm install -g polymer-cli` or via `yarn` or `pnpm` or anything else that might not honor the `shrinkwrap.json`?

**Comment by Westbrook** [comment]
I do use `yarn`. But it seems like `polymer-cli` relies on a [package-lock.json](https://github.com/Polymer/tools/blob/master/packages/cli/package-lock.json), which I thought Yarn respected.

**Comment by Westbrook** [comment]
But the `shrinkwrap.json` does get put into the directory, interesting...that seems...less than opportune.

**Comment by Westbrook** [comment]
`yarn` being the issue also seems counter to the `yarn` based [compile from source](https://github.com/Polymer/tools/tree/master/packages/cli#compiling-from-source) instructions.

**Comment by Westbrook** [comment]
@usergenic I took another pass at this from `rm -rf node_modules` with `npm install` and still no luck. The error moved around a little bit, but other wise it's much the same:
```
SyntaxError: Unexpected token, expected ( (126:14)
    at Parser.pp$5.raise (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3632:14)
    at Parser.parseExprAtom (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/Users/westbrook/Documents/web/repos/ll-course-catalog/node_modules/istanbul-lib-instrument/node_modules/babylon/lib/index.js:6474:20)
```

Is there something special required in my `polymer.json` to make this work?

**Comment by Westbrook** [comment]
Further investigation has this looking like it is tied to a mismatch between the babel the CLI/WCT need and that of one of the WCT plugins that I'm using. Feel free to check out the process of digging into that here: https://github.com/Bubbit/wct-istanbub/issues/15
