### ISSUE TITLE
web-component-tester 6.7.1. don't work in node6

### ISSUE THREAD

**Issue by fqj** [Polymer/tools#593]
## Description

    I am trying to run the wct tests on my local machine. 

## Versions & Environment

        OS: mac version 10.12.6, 64 bit
        java version: 9.0.4
        node version: 6.11.3
        npm version: 5.1.0
        polymer: 2
        web-component-tester: 6.7.1
        wct-local:2.1.1
        selenium standalone: selenium-server-standalone-3.12.0.jar
        chrome browser: Version 67.0.3396.99

## Steps to Reproduce

    * I recently upgraded my web-component-tester version to 6.7.1. 
    * This upgrade also causes an upgrade in wct-local dependency to 2.1.1. 
    * This finally causes an error because there is a function which is built-in in node8, but don't exist 
 in node6.

## Expected Results

    Should run the wct tests on my local machine.

## Actual Results
```
    [07/17/2018 4:25:55 PM] [ERROR] TypeError: util_1.promisify is not a function
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:49:30
        at next (native)
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:20:71
        at __awaiter (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:16:12)
        at unglob (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:47:12)
        at Object.<anonymous> (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:39:49)
        at next (native)
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:20:71
        at __awaiter (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:16:12)
        at Object.expand (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:38:12)
```

## Solution

    I solved my problem downgrading my web-component-tester dependency to version 6.5.0 and setting the wct-local dependency's version to 2.1.0.

**Comment by fqj** [comment]
## Description

    I am trying to run the wct tests on my local machine. 

## Versions & Environment

        OS: mac version 10.12.6, 64 bit
        java version: 9.0.4
        node version: 6.11.3
        npm version: 5.1.0
        polymer: 2
        web-component-tester: 6.7.1
        wct-local:2.1.1
        selenium standalone: selenium-server-standalone-3.12.0.jar
        chrome browser: Version 67.0.3396.99

## Steps to Reproduce

    * I recently upgraded my web-component-tester version to 6.7.1. 
    * This upgrade also causes an upgrade in wct-local dependency to 2.1.1. 
    * This finally causes an error because there is a function which is built-in in node8, but don't exist 
 in node6.

## Expected Results

    Should run the wct tests on my local machine.

## Actual Results
```
    [07/17/2018 4:25:55 PM] [ERROR] TypeError: util_1.promisify is not a function
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:49:30
        at next (native)
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:20:71
        at __awaiter (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:16:12)
        at unglob (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:47:12)
        at Object.<anonymous> (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:39:49)
        at next (native)
        at /Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:20:71
        at __awaiter (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:16:12)
        at Object.expand (/Users/foqr/.nvm/versions/node/v6.11.3/lib/node_modules/web-component-tester/runner/paths.js:38:12)
```

## Solution

   I solved my problem downgrading my web-component-tester dependency to version 6.5.0 and setting the wct-local dependency's version to 2.1.0.

**Comment by aomarks** [comment]
Sorry, we no longer support Node 6. You'll need to upgrade to 8.0 or 10.0 to use new versions of the tools. See https://www.polymer-project.org/3.0/docs/tools/node-support for our Node version support policy.

**Comment by ifisidro** [comment]
Shouldn't have it been tagged with a major version? It will break our tools that wrap web-component-tester and will force our users to upgrade to Node 8.0 or greater. I know that updating isn't a challenge but I don't agree with the adopted tagging policy.
