### ISSUE TITLE
[cli] polymer test command no longer accepts test file

### ISSUE THREAD

**Issue by jimivdw** [Polymer/tools#657]
One of the projects I work on has a lot of tests. Therefore, while developing, I mostly run only a single test file via `polymer test test/my-component_test.html`.

Somewhere between version `1.7.2` and `1.7.7` of the CLI this stopped working, however, and now gives an error in the command args parser:
```
error: [cli.main]   cli runtime exception: UNKNOWN_VALUE: Unknown value: test/my-component_test.html
error: [cli.main]   UNKNOWN_VALUE: Unknown value: test/my-component_test.html
    at commandLineArgs ([...]/node_modules/polymer-cli/node_modules/command-line-args/index.js:54:21)
    at PolymerCli.<anonymous> ([...]/node_modules/polymer-cli/lib/polymer-cli.js:172:39)
    at Generator.next (<anonymous>)
    at [...]/node_modules/polymer-cli/lib/polymer-cli.js:20:71
    at new Promise (<anonymous>)
    at __awaiter ([...]/node_modules/polymer-cli/lib/polymer-cli.js:16:12)
    at PolymerCli.run ([...]/node_modules/polymer-cli/lib/polymer-cli.js:138:16)
    at Object.<anonymous> ([...]/node_modules/polymer-cli/lib/run.js:39:34)
    at Generator.next (<anonymous>)
    at [...]/node_modules/polymer-cli/lib/run.js:20:71
```

Running the same via the `wct` cli still _does_ work.

Side note: also tested and still failing in `1.8.0`.

**Comment by Sanyusha** [comment]
Does it have some workaround? I have this issue on polymer 1.9.5 as well.

**Comment by jimivdw** [comment]
Not really, afaik. I ended up downgrading to `1.7.2` and one of my colleagues switched to using `wct` directly. You could also edit your `wct.conf` file to only load the test files you wish to load, but then you would need to edit that file all the time. Hope the args parser can just be fixed.
