### ISSUE TITLE
polymer help lint broken

### ISSUE THREAD

**Issue by msi-matthew** [Polymer/tools#698]
Using macOS mojave and Polymer v 1.8.0

I get the following error when running `polymer help lint` from the command line.

```error: [cli.main]   cli runtime exception: Error: Found extraneous } in Chalk template literal
error: [cli.main]   Error: Found extraneous } in Chalk template literal
    at tmp.replace (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/node_modules/chalk/templates.js:109:11)
    at String.replace (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/node_modules/chalk/templates.js:99:6)
    at chalkTag (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/node_modules/chalk/index.js:221:9)
    at Chalk.chalk.template (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/node_modules/chalk/index.js:36:20)
    at format (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/lib/chalk-format.js:4:10)
    at chalkFormat (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/lib/chalk-format.js:10:12)
    at ContentSection.arrayify.map.line (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/lib/content-section.js:14:63)
    at Array.map (<anonymous>)
    at new ContentSection (/usr/local/lib/node_modules/polymer-cli/node_modules/command-line-usage/lib/content-section.js:14:51)```

**Comment by daniele-orlando** [comment]
Same here.

**MacOS 10.13** and **Polymer 1.8.0**.
