### ISSUE TITLE
[bundler] Possible problem with latest version of chalk and bundler CLI

### ISSUE THREAD

**Issue by usergenic** [Polymer/tools#741]
So...
```
~/s/g/P/pwa-starter-kit-hn master λ nvm use 10
Now using node v10.9.0 (npm v6.4.1)
~/s/g/P/pwa-starter-kit-hn master λ npm install -g polymer-bundler
/Users/brendanb/.nvm/versions/node/v10.9.0/bin/polymer-bundler -> /Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/lib/bin/polymer-bundler.js
+ polymer-bundler@4.0.3
added 127 packages from 243 contributors in 3.471s
~/s/g/P/pwa-starter-kit-hn master λ polymer-bundler -h
/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/node_modules/chalk/templates.js:109
                                throw new Error('Found extraneous } in Chalk template literal');
                                ^

Error: Found extraneous } in Chalk template literal
    at tmp.replace (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/node_modules/chalk/templates.js:109:11)
    at String.replace (<anonymous>)
    at module.exports (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/node_modules/chalk/templates.js:99:6)
    at chalkTag (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/node_modules/chalk/index.js:221:9)
    at Chalk.chalk.template (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/node_modules/chalk/index.js:36:20)
    at format (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/lib/chalk-format.js:4:10)
    at chalkFormat (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/lib/chalk-format.js:10:12)
    at getOptionNames (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/lib/option-list.js:66:10)
    at OptionList.definitions.map.def (/Users/brendanb/.nvm/versions/node/v10.9.0/lib/node_modules/polymer-bundler/node_modules/command-line-usage/lib/option-list.js:40:17)
    at Array.map (<anonymous>)
```

**Comment by usergenic** [comment]
Fixed in #742
