### ISSUE TITLE
build fails with Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by govis** [Polymer/tools#753]
Hi,

Trying to build a Polymer 3 project, but getting the following error: <pre><code>error: [cli.main]   Promise rejection: Error: Unable to get document file://.../fragment1.js: Error while scanning: TypeError: Cannot read property 'file' of undefined
error: [cli.main]   Error: Unable to get document file://.../fragment1.js: Error while scanning: TypeError: Cannot read property 'file' of undefined
    at Object.getAnalysisDocument (C:\Users\...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\analyzer-utils.js:10:15)
    at Bundler.<anonymous> (C:\Users\...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\bundler.js:83:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\bundler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)</code></pre>

Unfortunately it doesn't say which file is the actual culprit as fragment1.js simply contains a few imports that all resolve to valid files like so: 

<pre><code>import './element1.js';
import './element2.js';
import './element3.js';
import './element4.js';
import './element5.js';</code></pre>

 I narrowed it down to one of the imports (lets say element4.js) and if I comment it out everything builds fine. Unfortunately there seems to be nothing wrong with either fragment1.js or element4.js as I can bundle them individually with both <code>polymer-bundler</code> and <code>rollup</code>.

It only fails when I run the <code>polymer build</code> on the whole project:<pre><code>{
  "entrypoint": "index.html",
  "shell": "app-main.js",
  "fragments": [
    "fragment1.js"
  ],
  "sources": [
  ],
  "extraDependencies": [
    "node_modules/@webcomponents/webcomponentsjs/**"
  ],
  "builds": [
    {
      "name": "esm-bundled",
      "browserCapabilities": [
        "es2015",
        "modules"
      ],
      "js": {
        "minify": true
      },
      "css": {
        "minify": true
      },
      "html": {
        "minify": true
      },
      "bundle": true
    }
  ],
  "moduleResolution": "node",
  "npm": true,
  "lint": {
    "rules": [ "polymer-3" ]
  }
}</code></pre>

Also, <code>polymer build -v</code> doesn't provide any useful info but a ton of <code>debug: [cli.build.analyzer] unexpected import type encountered: js-import</code> noise.

On a related note when I saw <code>Unable to get document file://....js: Error while scanning: TypeError: Cannot read property 'file' of undefined</code> errors in the past I could not get the actual file name from the error and had to resort to calling <code>rollup</code> directly to find out which file was problematic, so error reporting in <code>polymer build</code> may need to be improved.

Thank you

**Comment by govis** [comment]
Getting a different error now that maybe related:

<pre><code>error:  Promise rejection: Error: Unable to get document file:///.../fragment1.js: Error while scanning: TypeError: Cannot read property 'buildError' of undefined
error:  Error: Unable to get document file:///.../fragment1.js: Error while scanning: TypeError: Cannot read property 'buildError' of undefined
    at Object.getAnalysisDocument (C:\Users...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\analyzer-utils.js:10:15)
    at Bundler.<anonymous> (C:\Users...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\bundler.js:83:47)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users...\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\polymer-bundler\lib\bundler.js:4:58)
    at &lt;anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)</code></pre>
