### ISSUE TITLE
Error: Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by jarrodek** [Polymer/tools#816]
I just installed `gen-typescript-declarations` version 1.6.0 and I got the following error when running the command:

```
gen-typescript-declarations --deleteExisting --outDir .
```

```
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'source-map-support/register'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ppsztyc/workspace/arc/form-data-editor/node_modules/@polymer/gen-typescript-declarations/lib/cli.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
```

This was working perfectly with previous version.

Known workaround:

```
npm i --no-save source-map-support
```

**Comment by jarrodek** [comment]
The problem is that the `source-map-support` library is defined as dev dependency: https://github.com/Polymer/tools/blob/ffed1e3c165ed24da233fff8f7de320d65f6f64b/packages/gen-typescript-declarations/package.json#L42 and it is used in `src/cli.ts` https://github.com/Polymer/tools/blob/ffed1e3c165ed24da233fff8f7de320d65f6f64b/packages/gen-typescript-declarations/src/cli.ts#L12

It should be moved to dependencies list.

**Comment by vplugues** [comment]
you should not have to move them to the dependecy list.

Just install them `npm install --dev`

**Comment by jarrodek** [comment]
@vplugues this wouldn't help here. It doesn't matter whether the package was installed in my application via -S or -D or how I install packages (it's always `npm i`). It the dependency in foreign package is installed as dev but used in the main library code it will throw this error as dev dependencies of the library you are installing are not included into the installation list (not it should be).

**Comment by vplugues** [comment]
well @jarrodek  it worked for me when I installed the devDependencies. You should try it. There shouldn't be a need to move the packages.

**Comment by jarrodek** [comment]
What I mean @vplugues you shouldn't be required to do this. The package is fixed now anyway.
