### ISSUE TITLE
[BUILD] project fails to build linux

### ISSUE THREAD

**Issue by RobMaskell** [Polymer/tools#834]
Trying to fix an issue where I think a babel helper is missing, so forked the tools repo and tried to build with

```
npm install
npm run bootstrap
npm run build
```
and it fails, the log output is
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.5.0
3 info using node@v10.14.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle polymer-tools@~prebuild: polymer-tools@
6 info lifecycle polymer-tools@~build: polymer-tools@
7 verbose lifecycle polymer-tools@~build: unsafe-perm in lifecycle true
8 verbose lifecycle polymer-tools@~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/robm/projects/tools/node_modules/.bin:/opt/terraform:/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle polymer-tools@~build: CWD: /home/robm/projects/tools
10 silly lifecycle polymer-tools@~build: Args: [ '-c', 'lerna run build --stream' ]
11 silly lifecycle polymer-tools@~build: Returned: code: 2  signal: null
12 info lifecycle polymer-tools@~build: Failed to exec build script
13 verbose stack Error: polymer-tools@ build: `lerna run build --stream`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid polymer-tools@
15 verbose cwd /home/robm/projects/tools
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v10.14.2
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 2
22 error polymer-tools@ build: `lerna run build --stream`
22 error Exit status 2
23 error Failed at the polymer-tools@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
and some more info on exactly what went wrong
```

> polymer-tools@ build /home/robm/projects/tools
> lerna run build --stream

lerna notice cli v3.8.0
lerna info versioning independent
lerna info Executing command in 19 packages: "npm run build"
dom5: > dom5@3.0.1 build /home/robm/projects/tools/packages/dom5
dom5: > tsc
cleankill: > cleankill@2.0.0 build /home/robm/projects/tools/packages/cleankill
cleankill: > npm run clean && tsc && npm run lint
browser-capabilities: > browser-capabilities@1.1.3 build /home/robm/projects/tools/packages/browser-capabilities
browser-capabilities: > rm -Rf lib/ && tsc && npm run lint
@polymer/esm-amd-loader: > @polymer/esm-amd-loader@1.0.4 build /home/robm/projects/tools/packages/esm-amd-loader
@polymer/esm-amd-loader: > npm run clean && tsc && npm run minify && npm run lint
cleankill: > cleankill@2.0.0 clean /home/robm/projects/tools/packages/cleankill
cleankill: > rm -f *.js *.d.ts
@polymer/esm-amd-loader: > @polymer/esm-amd-loader@1.0.4 clean /home/robm/projects/tools/packages/esm-amd-loader
@polymer/esm-amd-loader: > rm -rf lib/
browser-capabilities: > browser-capabilities@1.1.3 lint /home/robm/projects/tools/packages/browser-capabilities
browser-capabilities: > tslint -p .
wct-mocha: > wct-mocha@1.0.0 build /home/robm/projects/tools/packages/wct-mocha
wct-mocha: > npm run build:compile && npm run build:browserjs
wct-mocha: > wct-mocha@1.0.0 build:compile /home/robm/projects/tools/packages/wct-mocha
wct-mocha: > tsc
cleankill: > cleankill@2.0.0 lint /home/robm/projects/tools/packages/cleankill
cleankill: > tslint -p .
@polymer/esm-amd-loader: > @polymer/esm-amd-loader@1.0.4 minify /home/robm/projects/tools/packages/esm-amd-loader
@polymer/esm-amd-loader: > babel-minify lib/esm-amd-loader.js --outFile=lib/esm-amd-loader.min.js
polymer-workspaces: > polymer-workspaces@2.2.0 build /home/robm/projects/tools/packages/workspaces
polymer-workspaces: > tsc && npm run lint
@polymer/esm-amd-loader: > @polymer/esm-amd-loader@1.0.4 lint /home/robm/projects/tools/packages/esm-amd-loader
@polymer/esm-amd-loader: > tslint -p . --format stylish
wct-mocha: > wct-mocha@1.0.0 build:browserjs /home/robm/projects/tools/packages/wct-mocha
wct-mocha: > rollup -c
polymer-workspaces: > polymer-workspaces@2.2.0 lint /home/robm/projects/tools/packages/workspaces
polymer-workspaces: > tslint -p .
wct-mocha: lib/browser.js → wct-mocha.js...
wct-mocha: (!) Circular dependency: lib/childrunner.js -> lib/util.js -> lib/config.js -> lib/childrunner.js
wct-mocha: (!) Circular dependency: lib/util.js -> lib/config.js -> lib/util.js
wct-mocha: (!) Circular dependency: lib/childrunner.js -> lib/util.js -> lib/config.js -> commonjs-proxy:/home/robm/projects/tools/packages/wct-mocha/lib/childrunner.js -> lib/childrunner.js
wct-mocha: (!) Circular dependency: lib/util.js -> lib/config.js -> commonjs-proxy:/home/robm/projects/tools/packages/wct-mocha/lib/util.js -> lib/util.js
wct-mocha: created wct-mocha.js in 361ms
polymer-analyzer: > polymer-analyzer@3.2.1 build /home/robm/projects/tools/packages/analyzer
polymer-analyzer: > tsc && npm run generate-json-schema && npm run tslint
wct-local: > wct-local@2.1.3 build /home/robm/projects/tools/packages/wct-local
wct-local: > tsc && npm run lint
wct-local: > wct-local@2.1.3 lint /home/robm/projects/tools/packages/wct-local
wct-local: > tslint -p .
polymer-analyzer: > polymer-analyzer@3.2.1 generate-json-schema /home/robm/projects/tools/packages/analyzer
polymer-analyzer: > typescript-json-schema --required --ignoreErrors src/analysis-format/analysis-format.ts -o lib/analysis.schema.json Analysis
polymer-analyzer: > polymer-analyzer@3.2.1 tslint /home/robm/projects/tools/packages/analyzer
polymer-analyzer: > tslint -p .
polymer-bundler: > polymer-bundler@4.0.4 build /home/robm/projects/tools/packages/bundler
polymer-bundler: > tsc && npm run lint
polymer-project-config: > polymer-project-config@4.0.2 build /home/robm/projects/tools/packages/project-config
polymer-project-config: > tsc && typescript-json-schema src/index.ts ProjectOptions --ignoreErrors -o lib/schema.json && npm run lint
@polymer/gen-typescript-declarations: > @polymer/gen-typescript-declarations@1.6.0 build /home/robm/projects/tools/packages/gen-typescript-declarations
@polymer/gen-typescript-declarations: > npm run clean && tsc && npm run lint
polymer-modulizer: > polymer-modulizer@0.4.3 build /home/robm/projects/tools/packages/modulizer
polymer-modulizer: > tsc && npm run lint
@polymer/gen-typescript-declarations: > @polymer/gen-typescript-declarations@1.6.0 clean /home/robm/projects/tools/packages/gen-typescript-declarations
@polymer/gen-typescript-declarations: > rimraf lib
@polymer/gen-typescript-declarations: > @polymer/gen-typescript-declarations@1.6.0 lint /home/robm/projects/tools/packages/gen-typescript-declarations
@polymer/gen-typescript-declarations: > tslint --project . --format stylish
polymer-bundler: > polymer-bundler@4.0.4 lint /home/robm/projects/tools/packages/bundler
polymer-bundler: > tslint -p .
polymer-modulizer: > polymer-modulizer@0.4.3 lint /home/robm/projects/tools/packages/modulizer
polymer-modulizer: > tslint -p .
polymer-project-config: > polymer-project-config@4.0.2 lint /home/robm/projects/tools/packages/project-config
polymer-project-config: > tslint -p .
polymer-build: > polymer-build@3.1.1 build /home/robm/projects/tools/packages/build
polymer-build: > npm run clean && tsc && node scripts/generate-helpers.js && npm run lint
polymer-linter: > polymer-linter@3.0.1 build /home/robm/projects/tools/packages/linter
polymer-linter: > npm run clean && tsc && npm run lint
polymer-build: > polymer-build@3.1.1 clean /home/robm/projects/tools/packages/build
polymer-build: > rm -rf lib/
polymer-linter: > polymer-linter@3.0.1 clean /home/robm/projects/tools/packages/linter
polymer-linter: > touch lib && rm -rf lib && mkdir lib
polymer-linter: > polymer-linter@3.0.1 lint /home/robm/projects/tools/packages/linter
polymer-linter: > tslint -p .
polymer-build: > polymer-build@3.1.1 lint /home/robm/projects/tools/packages/build
polymer-build: > tslint -p . && node scripts/depcheck.js
polyserve: > polyserve@0.27.14 build /home/robm/projects/tools/packages/polyserve
polyserve: > npm run clean && tsc && npm run lint
polymer-editor-service: > polymer-editor-service@2.2.2 build /home/robm/projects/tools/packages/editor-service
polymer-editor-service: > tsc && npm run lint
polyserve: > polyserve@0.27.14 clean /home/robm/projects/tools/packages/polyserve
polyserve: > rimraf lib
polymer-editor-service: > polymer-editor-service@2.2.2 lint /home/robm/projects/tools/packages/editor-service
polymer-editor-service: > tslint -p .
polyserve: > polyserve@0.27.14 lint /home/robm/projects/tools/packages/polyserve
polyserve: > tslint -p .
web-component-tester: > web-component-tester@6.9.2 build /home/robm/projects/tools/packages/web-component-tester
web-component-tester: > tsc && gulp build
web-component-tester: [19:53:28] Using gulpfile ~/projects/tools/packages/web-component-tester/gulpfile.js
web-component-tester: [19:53:28] Starting 'build'...
web-component-tester: [19:53:28] Starting 'build:typescript-server'...
web-component-tester: [19:53:30] Finished 'build:typescript-server' after 2.73 s
web-component-tester: [19:53:30] Starting 'build:browser'...
web-component-tester: [19:53:30] Starting 'build:typescript-browser'...
web-component-tester: [19:53:33] Finished 'build:typescript-browser' after 2.24 s
web-component-tester: [19:53:33] Starting '<anonymous>'...
web-component-tester: [19:53:33] Finished '<anonymous>' after 135 ms
web-component-tester: [19:53:33] Finished 'build:browser' after 2.38 s
web-component-tester: [19:53:33] Starting 'build:wct-browser-legacy'...
web-component-tester: [19:53:33] Starting 'build:wct-browser-legacy:a11ySuite'...
web-component-tester: [19:53:33] Finished 'build:wct-browser-legacy:a11ySuite' after 12 ms
web-component-tester: [19:53:33] Starting 'build:wct-browser-legacy:browser'...
web-component-tester: [19:53:33] Starting 'build:typescript-browser'...
web-component-tester: [19:53:34] Finished 'build:typescript-browser' after 1.58 s
web-component-tester: [19:53:34] Starting '<anonymous>'...
web-component-tester: [19:53:34] Finished '<anonymous>' after 92 ms
web-component-tester: [19:53:34] Finished 'build:wct-browser-legacy:browser' after 1.67 s
web-component-tester: [19:53:34] Finished 'build:wct-browser-legacy' after 1.69 s
web-component-tester: [19:53:34] Finished 'build' after 6.8 s
@polymer/esm-amd-loader-test: > @polymer/esm-amd-loader-test@0.1.0 build /home/robm/projects/tools/packages/esm-amd-loader/test
@polymer/esm-amd-loader-test: > npm run clean && tsc
polymer-cli: > polymer-cli@1.9.4 build /home/robm/projects/tools/packages/cli
polymer-cli: > npm run clean && tsc && npm run lint
@polymer/esm-amd-loader-test: > @polymer/esm-amd-loader-test@0.1.0 clean /home/robm/projects/tools/packages/esm-amd-loader/test
@polymer/esm-amd-loader-test: > rm -rf lib/
polymer-cli: > polymer-cli@1.9.4 clean /home/robm/projects/tools/packages/cli
polymer-cli: > rm -rf lib/
polymer-cli: src/test/integration/integration_test.ts:554:7 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
polymer-cli: 554       this.timeout(30 * 1000);
polymer-cli:           ~~~~
polymer-cli:   src/test/integration/integration_test.ts:552:20
polymer-cli:     552     test(testName, async function() {
polymer-cli:                            ~~~~~
polymer-cli:     An outer value of 'this' is shadowed by this container.
polymer-cli: src/test/integration/integration_test.ts:632:7 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
polymer-cli: 632       this.timeout(30 * 1000);
polymer-cli:           ~~~~
polymer-cli:   src/test/integration/integration_test.ts:630:20
polymer-cli:     630     test(testName, async function() {
polymer-cli:                            ~~~~~
polymer-cli:     An outer value of 'this' is shadowed by this container.
polymer-cli: Found 2 errors.
polymer-cli: npm ERR! code ELIFECYCLE
polymer-cli: npm ERR! errno 2
polymer-cli: npm ERR! polymer-cli@1.9.4 build: `npm run clean && tsc && npm run lint`
polymer-cli: npm ERR! Exit status 2
polymer-cli: npm ERR! 
polymer-cli: npm ERR! Failed at the polymer-cli@1.9.4 build script.
polymer-cli: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
polymer-cli: npm ERR! A complete log of this run can be found in:
polymer-cli: npm ERR!     /home/robm/.npm/_logs/2018-12-25T19_53_39_409Z-debug.log
lerna ERR! npm run build exited 2 in 'polymer-cli'
lerna ERR! npm run build stdout:

> polymer-cli@1.9.4 build /home/robm/projects/tools/packages/cli
> npm run clean && tsc && npm run lint


> polymer-cli@1.9.4 clean /home/robm/projects/tools/packages/cli
> rm -rf lib/

src/test/integration/integration_test.ts:554:7 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

554       this.timeout(30 * 1000);
          ~~~~

  src/test/integration/integration_test.ts:552:20
    552     test(testName, async function() {
                           ~~~~~
    An outer value of 'this' is shadowed by this container.

src/test/integration/integration_test.ts:632:7 - error TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.

632       this.timeout(30 * 1000);
          ~~~~

  src/test/integration/integration_test.ts:630:20
    630     test(testName, async function() {
                           ~~~~~
    An outer value of 'this' is shadowed by this container.


Found 2 errors.


lerna ERR! npm run build stderr:
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! polymer-cli@1.9.4 build: `npm run clean && tsc && npm run lint`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the polymer-cli@1.9.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robm/.npm/_logs/2018-12-25T19_53_39_409Z-debug.log

lerna ERR! npm run build exited 2 in 'polymer-cli'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! polymer-tools@ build: `lerna run build --stream`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the polymer-tools@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
If I can get it building hopefully I can fix the issue with the babel helper and submit a PR, any ideas?

**Comment by TimvdLippe** [comment]
I just ran another build on Linux and with success. Looking at the failure, it seems that the wrong version of a package was loaded. Travis is also happy.

Not sure how to triage this issue, as I am unable to reproduce and don't understand why it would suddenly fail. Are you still able to reproduce this issue?

**Comment by RobMaskell** [comment]
The CI wasn't happy on the PR I submitted at about the same time. I'll clone the repo again and try it from the top see if it will build that way, if not I'll post the commands I used in case I did something wrong.

**Comment by TimvdLippe** [comment]
No problem at all! Feel free to make another issue if you encounter future
build issues.
