### ISSUE TITLE
mistyping of a behaviors property caused output window to open and display error

### ISSUE THREAD

**Issue by akc42** [Polymer/tools#916]
I was just starting to type in this snipped of code
```
      _toggleListFull: function(e) {
        if (this.user.isManager) {

        }
      }
```
And was in this the body of the iff statement and trying to type when the following error was triggered
```
[Error - 09:43:36] Error: Expected to find at most one behavior with id PAS.User but found 2.
    at InlineDocument.getOnlyAtId (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/document.js:156:19)
    at _getFlattenedAndResolvedBehaviors (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/polymer/polymer-element.js:123:40)
    at getFlattenedAndResolvedBehaviors (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/polymer/polymer-element.js:118:5)
    at resolveElement (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/polymer/polymer-element.js:105:34)
    at ScannedPolymerElement.resolve (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/polymer/polymer-element.js:67:16)
    at InlineDocument.resolve (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/document.js:102:48)
    at ScannedInlineDocument.resolve (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/inline-document.js:41:24)
    at Document.resolve (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/document.js:102:48)
    at Analyzer._makeDocument (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:154:18)
    at Analyzer.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:132:39)
```

`PAS.User` is a behavior that had been html imported once at the top of the file and included correctly as a behavior
```
      behaviors: [
        PAS.DateUtils,
        Polymer.NeonSharedElementAnimatableBehavior,
        Polymer.IronResizableBehavior,
        PAS.User
      ],

```
It provides a `user` object, but also provides amongst other things the property `isManager`;

The mistake I made here is that that if statement should have been
```
      _toggleListFull: function(e) {
        if (this.isManager) {

        }
      }
```
ie `isManager` is a property of `this` and not `this.user`

Once I had the error I report above, any typing in the iff statement or even having the mouse pass over the text -caused the output window to pop up.  I could only get stable enough to edit the code by shutting down vscode (which is what I am using) and starting it up again.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
