### ISSUE TITLE
Rapid Backspacing can throw up an "already exists" error for file you are editing

### ISSUE THREAD

**Issue by akc42** [Polymer/tools#917]
Using vscode, I quite frequently get the following pop up in an OUTPUT window from polymer-ide.

```
[Error - 13:59:20] Error: Internal error: document app/src/pas-appointments-day.html already exists
    at Analyzer._makeDocument (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:147:19)
    at Analyzer.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:132:39)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[Error - 13:59:20] Error: Internal error: document app/src/pas-appointments-day.html already exists
    at Analyzer._makeDocument (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:147:19)
    at Analyzer.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:132:39)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/analyzer.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)

etc etc ........................
```
It happens on back-delete.

I suspect I am getting one new message per key press, but it has to be keyboard repeat to go fast enough to trigger it, so cannot be sure.  It doesn't seem to trigger in text or element attributes - but it seems to wait until you are in the actual element name. This name doesn't have to be real.

If you stop, and try and repeat it, it doesn't happen again until you clear and close the output window. Then its easily repeatable.

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
