### ISSUE TITLE
Miss interpreting id?

### ISSUE THREAD

**Issue by akc42** [Polymer/tools#918]
I have the following section of html in my element template
```
     <section id="hero_target" class="main-heading">
          <div class="heading">[[_makeHeading(clinic,route.params.date)]]</div>
          <paper-icon-button
            on-tap="_setFullOn"
            icon="pas:zoom-in"
            hidden$="[[subRoute.active]]"></paper-icon-button>
          <paper-icon-button
            on-tap="_setFullOff"
            icon="pas:zoom-out"
            hidden$="[[!subRoute.active]]"></paper-icon-button>
          <paper-icon-button
            on-tap="_openDrawer"
            icon="pas:info-outline"></paper-icon-button>
      </section>
  
```
As I mouse over the start of the `<paper-icon-button>` tag the following pops up in the output

```
[Error - 09:01:25] Error: Expected to find at most one element with id paper-icon-button but found 2.
    at Document.getOnlyAtId (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/model/document.js:156:19)
    at LocalEditorService.<anonymous> (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/editor-service/local-editor-service.js:157:33)
    at next (<anonymous>)
    at fulfilled (/home/alan/.vscode/extensions/polymer.polymer-ide-0.1.2/server/node_modules/polymer-analyzer/lib/editor-service/local-editor-service.js:17:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Using vscode

**Comment by aomarks** [comment]
Re-opening because this original issue is now transferred and canonical again.
