### ISSUE TITLE
Issue on the post-install script behind corporate proxy

### ISSUE THREAD

**Issue by jmorille** [Polymer/tools#945]
On Ubuntu 13.04, behing a corporate proxy I have this error (same as https://github.com/Polymer/wct-sauce/issues/3 ) :

```
~/someFolder$ npm install -g wct-sauce

> sauce-connect-launcher@0.9.3 postinstall /home/a000cqp/opt/nodejs/lib/node_modules/wct-sauce/node_modules/sauce-connect-launcher
> node scripts/install.js

/
> wct-sauce@1.2.0 postinstall /home/a000cqp/opt/nodejs/lib/node_modules/wct-sauce
> node scripts/postinstall.js

Prefetching the Sauce Connect binary.
Missing Sauce Connect local proxy, downloading dependency
This will only happen once.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ETIMEDOUT
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)

npm ERR! wct-sauce@1.2.0 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the wct-sauce@1.2.0 postinstall script.
npm ERR! This is most likely a problem with the wct-sauce package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls wct-sauce
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/home/a000cqp/opt/nodejs/bin/node" "/home/a000cqp/opt/nodejs/bin/npm" "install" "-g" "wct-sauce"
npm ERR! cwd /home/a000cqp/project/tt-components/tt-crud
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

They a way to activate a verbose mode, in order to check the correct reading of system env http_proxy, https_proxy, no_proxy?

**Comment by jmorille** [comment]
Dead project
